Feat/hit and blow giveup
danielkaneko/HitAndBlow pull request #11
Opened 2022-08-12 06:01 UTC by danielkaneko

@nabemasamasa 
@Takatatsu9 

ギブアップ機能を追加いたしました。
ご確認、レビューをお願いいたします。

2022-08-12 06:54 UTC, Takatatsu9 commented
PRタイトル直してね

2022-08-12 06:57 UTC, danielkaneko commented
PRタイトルを修正いたしました。

2022-08-12 07:00 UTC, nabemasamasa requested changes, later dismissed
NG

2022-08-12 07:00 UTC, nabemasamasa commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
[imo] Nullの場合のテストが欲しいです。メソッド単体での機能の保証として。

2022-08-12 07:00 UTC, nabemasamasa commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
[imo] Falseを返すパターンが欲しいです。テストを作るなら、両方のパターンがほしいです。

2022-08-12 07:00 UTC, nabemasamasa commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public giveUp As Boolean = False
[MUST] Publicは……Booleanは……

2022-08-12 07:00 UTC, nabemasamasa commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> +    Public Sub IsMeaningfulInputがgiveupを通すこと()
[IMO] Falseを返すパターンがほしいです。
後、「○○ならXXを返す」の方が望ましいです。

2022-08-12 07:00 UTC, nabemasamasa commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return False
[imo] 1行で書けそうです

2022-08-12 07:03 UTC, danielkaneko commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
レビューありがとうございます。
Nullの場合のテストを追加いたします。

2022-08-12 07:04 UTC, danielkaneko commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
レビューありがとうございます。
Falseを返すパターンのテストを追加いたします。

2022-08-12 07:07 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public giveUp As Boolean = False
レビューありがとうございます。
変数名を修正いたします。

2022-08-12 07:08 UTC, danielkaneko commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> +    Public Sub IsMeaningfulInputがgiveupを通すこと()
レビューありがとうございます。
Falseを返すパターンのテストを追加いたします。
テストメソッド名を修正いたします。

2022-08-12 07:09 UTC, danielkaneko commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return False
レビューありがとうございます。
１行で納められるよう修正いたします。

2022-08-12 07:29 UTC, Takatatsu9 reviewed
Done

2022-08-12 07:29 UTC, Takatatsu9 commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public giveUp As Boolean = False
3回目
<img src="https://user-images.githubusercontent.com/50448373/184305347-d8964609-6610-4d34-8f87-c5aa85dbf11c.png" width="400">

2022-08-12 07:29 UTC, Takatatsu9 commented on HitAndBlow/MeaningfulInputCheck.vb
> +        Return giveUp OrElse ianc.IsInputAnswerNumber(answerNumber, questionNumber)
[nits] 変数化するなら`IsInputAnswerNumber`も変数化したほうがよくない？
`IsInputAnswerNumber`がベタ書きなら`IsInputGiveUp`もベタ書きでよくない？

2022-08-12 07:55 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public giveUp As Boolean = False
レビューありがとうございます。
大変申し訳ございません。
コメントを追加いたします。

2022-08-12 07:57 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +        Return giveUp OrElse ianc.IsInputAnswerNumber(answerNumber, questionNumber)
レビューありがとうございます。
IsInputAnswerNumberを変数化し、統一いたします。

2022-08-22 05:28 UTC, danielkaneko commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
修正いたしました。
コミットハッシュ： 201add8

2022-08-22 05:28 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public giveUp As Boolean = False
修正いたしました。
コミットハッシュ： 4f61ba2

2022-08-22 05:29 UTC, danielkaneko commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
修正いたしました。
コミットハッシュ： bf59c98

2022-08-22 05:30 UTC, danielkaneko commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return False
修正いたしました。
コミットハッシュ： a47648b

2022-08-22 05:30 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public giveUp As Boolean = False
修正いたしました。
コミットハッシュ： 4f61ba2

2022-08-22 05:30 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +        Return giveUp OrElse ianc.IsInputAnswerNumber(answerNumber, questionNumber)
修正いたしました。
コミットハッシュ： c68c88d

2022-08-22 06:10 UTC, danielkaneko commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> +    Public Sub IsMeaningfulInputがgiveupを通すこと()
修正いたしました。
コミットハッシュ：Falseを返すパターンのテストを追加 0d2c9d1
テストメソッド名を修正  d4bda56

2022-08-22 06:11 UTC, Takatatsu9 reviewed
Done

2022-08-22 06:11 UTC, Takatatsu9 commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return Not inputContent = String.Empty AndAlso "giveup".Equals(inputContent.ToLower())
[IMO] あれ？文字列の比較は`.Equals`でやるようにって言ってませんでしたっけ？
発言者俺じゃないにしても絶対伝えられてる気がする

2022-08-22 06:32 UTC, danielkaneko commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return Not inputContent = String.Empty AndAlso "giveup".Equals(inputContent.ToLower())
レビューありがとうございます。
おっしゃる通り、以前伝えられていたと思います。
大変申し訳ございません。
修正いたします。

2022-08-22 06:47 UTC, danielkaneko commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return Not inputContent = String.Empty AndAlso "giveup".Equals(inputContent.ToLower())
修正いたしました。
コミットハッシュ： 7a936dc

2022-08-23 01:06 UTC, nabemasamasa reviewed
NGのまま

2022-08-23 01:06 UTC, nabemasamasa commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +        Dim actual As Boolean = ianc.IsInputGiveUp("")
これはNullじゃない。`Nothing`がNull。`""`は空文字という。
空文字は長さ0の文字列だからインスタンスもあるし、メソッド呼び出してもぬるぽエラーは起きない。

2022-08-23 01:06 UTC, nabemasamasa commented on HitAndBlow/MeaningfulInputCheck.vb
> +        Dim IsAnswerNumber As Boolean = ianc.IsInputAnswerNumber(answerNumber, questionNumber)
[MUST:コーディングルール違反] ローカル変数なら……

2022-08-23 01:06 UTC, nabemasamasa commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> +    <Test>
`<TestCase>`なら`<Test>`まで書かなくてもテスト実行されてくれるので、書かなくても大丈夫です。

2022-08-23 01:09 UTC, nabemasamasa commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +    Public Sub IsInputGiveUpが大文字小文字関係なくgiveupを通すこと()
NGです、それはNullとはいわないです。

2022-08-23 01:26 UTC, Takatatsu9 reviewed
Done

2022-08-23 01:26 UTC, Takatatsu9 commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return Not inputContent.Equals(String.Empty) AndAlso "giveup".Equals(inputContent.ToLower())
[IMO] これは言ってましたっけ、言ってませんでしたっけ。
`可変の値.Equals(固定の値)`で可変の値がNULLだとどうなるでしょうか

2022-08-23 02:06 UTC, danielkaneko commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +        Dim actual As Boolean = ianc.IsInputGiveUp("")
レビューありがとうございます。
空文字をNullに修正いたします。

2022-08-23 02:06 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +        Dim IsAnswerNumber As Boolean = ianc.IsInputAnswerNumber(answerNumber, questionNumber)
レビューありがとうございます。
変数名を修正いたします。

2022-08-23 02:06 UTC, danielkaneko commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> +    <Test>
レビューありがとうございます。
不要な文字を削除いたします。

2022-08-23 02:06 UTC, danielkaneko commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return Not inputContent.Equals(String.Empty) AndAlso "giveup".Equals(inputContent.ToLower())
レビューありがとうございます。
以前ご指摘を頂いたかと思われます。
大変申し訳ございません。
修正いたします。

2022-08-23 05:25 UTC, danielkaneko commented on HitAndBlowTest/InputAnswerNumberCheckerTest.vb
> +        Dim actual As Boolean = ianc.IsInputGiveUp("")
修正いたしました。
コミットハッシュ： 6dc9708

2022-08-23 05:25 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +        Dim IsAnswerNumber As Boolean = ianc.IsInputAnswerNumber(answerNumber, questionNumber)
レビューありがとうございます。
変数名を修正いたします。

2022-08-23 05:26 UTC, danielkaneko commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> +    <Test>
修正いたしました。
コミットハッシュ： bafc011

2022-08-23 05:27 UTC, danielkaneko commented on HitAndBlow/InputAnswerNumberChecker.vb
> +        Return Not inputContent.Equals(String.Empty) AndAlso "giveup".Equals(inputContent.ToLower())
修正いたしました。
コミットハッシュ： cdc0aa0

2022-08-23 05:29 UTC, Takatatsu9 reviewed
Done

2022-08-23 05:29 UTC, Takatatsu9 commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> -    <Test>
> テストクラスにおける不要な文字の削除

それ文字じゃなくてコード・・・。コーディングにおける「文字」は`""`で囲われた部分ね・・・

2022-08-23 05:35 UTC, danielkaneko commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> -    <Test>
レビューありがとうございます。
コミットコメントを修正する形でよろしいでしょうか。

2022-08-23 05:37 UTC, Takatatsu9 commented on HitAndBlowTest/MeaningfulInputCheckTest.vb
> -    <Test>
多分言ってなかったと思いますけど、ラベル（`[IMO]`とか）をつけてないので独り言です。
直す必要どころか返信する必要もない、レビューですらない書き込みです。

2022-08-23 05:53 UTC, nabemasamasa reviewed
Done

2022-08-24 06:24 UTC, danielkaneko commented
コミット整理のため、強制プッシュを行いました。

2022-08-25 00:34 UTC, nabemasamasa reviewed
done

2022-08-25 00:34 UTC, nabemasamasa commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
コメント見たら意味がわかるけど、メソッド名を直訳すると「入力を登録する」……うーん……どこかに登録するの？ってなっちゃいそうです。

普通に「意味のある入力がされるまで待機する」から翻訳してメソッド名を作るのはどうですか？

2022-08-25 00:50 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
レビューありがとうございます。
メソッド名を修正いたします。

2022-08-25 02:23 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
修正いたしました。
コミットハッシュ： d4102b5

2022-08-25 04:32 UTC, nabemasamasa commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
レビューの負担になるので、Renameの差分だけのコミットにして、それのレビューを促すようにしてもらえませんか？？？？？？？？
↓のコミットの差分だと、合体済みの差分全部レビューしないといけなくて前回レビュー済みの範囲もレビューしないといけなくて、今回は未レビュー１コミットだからまだ負担少ないけど、つらいです。

> 修正いたしました。
> コミットハッシュ： https://github.com/danielkaneko/HitAndBlow/commit/d4102b54f2ff23e4d3b5e8ca5257e3b5b362a9dd

2022-08-25 04:53 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
配慮が足りず、申し訳ありませんでした。
今回のコミットをRenameno差分だけに分けてコミットをし直したほうが良いでしょうか？

2022-08-25 05:02 UTC, nabemasamasa commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
念の為、確認ですが[force-pushed](https://github.com/danielkaneko/HitAndBlow/compare/01954bd8043ac6f3409985aa1e2d0359b2100243..d4102b54f2ff23e4d3b5e8ca5257e3b5b362a9dd) の差分だけですよね？
もしそうなら、今回は対応しなくて大丈夫です。

2022-08-25 05:12 UTC, danielkaneko commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
今回はforce-pushedの差分のみです。
承知いたしました。

2022-08-25 05:19 UTC, nabemasamasa commented on HitAndBlow/MeaningfulInputCheck.vb
> +    Public Function RegisterInput(questionNumber As String) As String
確認ありがとうございます。
では、force-pushedの差分をレビューします。

2022-08-25 05:20 UTC, nabemasamasa reviewed
Done!

2022-08-25 05:38 UTC, Takatatsu9 reviewed
Done

2022-08-25 07:01 UTC, danielkaneko commented
基点ブランチを変更しましたので強制プッシュを行いました。

2022-08-26 00:54 UTC, nabemasamasa reviewed
Done

2022-08-29 05:21 UTC, Takatatsu9 reviewed
Done

2022-08-29 06:02 UTC, danielkaneko commented
コンフリクトが起きたため、基点ブランチを変更し強制プッシュを行いました。
何度も申し訳ございません。

2022-08-30 01:21 UTC, nabemasamasa reviewed
Done

2022-09-01 04:17 UTC, Takatatsu9 reviewed
Done

2022-09-02 05:12 UTC, merged