Hit&Blowを遊べるようにするため
danielkaneko/HitAndBlow pull request #2
Opened 2022-07-14 07:02 UTC by danielkaneko

@nabemasamasa
@Takatatsu9 
レビューをお願いいたします。

### ToDo
- [ ] 整数のみ通す入力チェック

2022-07-14 07:29 UTC, Takatatsu9 requested changes
Done

2022-07-14 07:29 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Loop
[MUST] 一気に全部実装して1コミットでドーン！はやめてほしいな・・・。
「実際に動かして確認できる1機能」につき「1コミット」が理想です。

- 良い例
    - 数値を入力できるようにする
        - （補足：数値入力を促すメッセージもこのコミットに含める）
    - 入力した数値に対し、ヒット数を表示する
    - 入力した数値に対し、ブロー数を表示する
    - ヒット4になるまでゲームを繰り返す
- 悪い例
    - 数値の入力を促すメッセージを表示する
    - 数値を入力できるようにする
    - 入力した数値を読み込む
    - 入力した数値に対し、ヒット数を数える
    - 数えたヒット数を画面に表示する
    - 入力した数値に対し、ブロー数を数える
    - 数えたブロー数を画面に表示する
    - ヒット4かをチェックする
    - ヒット4じゃなければゲームを繰り返す

2022-07-14 07:29 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
[IMO] こういった単体で完結する機能はクラス分けしてください。
目的はぷろぐらみんぐのおべんきょうではなく業務フローの学習ですので、
全て`Main`モジュールに突っ込むのはやめてください。

2022-07-14 07:54 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +    End Function
レビューありがとうございます。

ご指摘通り、機能のクラス分けを行います。
コミットの件につきましては申し訳ありませんでした。
以後このようなことがないよう、「実際に動かして確認できる1機能」につき「1コミット」をしてまいります。

2022-07-14 07:59 UTC, nabemasamasa requested changes
コーディングルール違反

2022-07-14 07:59 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Const GAMENUMBER As Integer = 4
コーディングルール違反、確かに全て大文字ですが、SNAKE_CASE、単語間はアンダースコア区切りです。
https://github.com/daniel-software-tokyo/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#13-%E5%AE%9A%E6%95%B0const-and-shared-readonly

2022-07-14 07:59 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +                If questionNumber.Substring(i, 1) = answerNumber.Substring(i, 1) Then
コーディングルール違反です、Stringの型同士の比較は、`.Equals`を使ってください。
https://github.com/daniel-software-tokyo/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#58-%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%90%8C%E5%80%A4%E6%AF%94%E8%BC%83

2022-07-14 07:59 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +                If IsNumeric(answerNumber) = True Then
If文は必ずBooleanなので、わざわざ`= True`させる必要はないですね……

2022-07-15 03:09 UTC, danielkaneko commented
@nabemasamasa
@Takatatsu9
レビューをお願いいたします。

2022-07-15 05:55 UTC, nabemasamasa requested changes
コミットメッセージとコードの差分の内容が……

2022-07-15 05:55 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Const GAME_NUMBER As Integer = 4
> 2701af39de33ac071452e3576ce69a11010a1bac : 数値設定機能のクラス分け

なんか余計な差分が混じりこんでませんか？
コミットコメントが表す作業の中に、定数名の修正やロジックの修正って別の作業をしてませんか？

2022-07-15 05:55 UTC, nabemasamasa commented on HitAndBlowTest/MainTest.vb
> -    <Test>
> 09aa858a50e8ab21acdc23e87b5eb699483e547f :  テストクラスの作成

このコミットの差分がないと、一個前のコミットってコンパイルエラー起きませんか？

[knowledge/git/git.beginner.md#コミットのルール](https://github.com/daniel-software-tokyo/knowledge/blob/master/git/Git.beginner.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB)
> 1. エラーが起こらないコミットにすること。
>    - 例: E2Eが通らない、Testが通らない、コンパイルが通らない…。

2022-07-15 05:55 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowTest.vbproj
> +    <Compile Include="QuestionNumberRegisterTest].vb" />
ファイル名と、クラス名一致してませんね……。

2022-07-15 05:55 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +                        If answerNumber.Length = 4 And answerNumber.Contains(".") = False Then
このあたりの入力チェック、メソッド抽出してテストできるようにすると良さそうですね。

逆にテストがないという事は、いちいちデバッグ実行して動作確認しないといけなくて手間ですし、
GitHubでPushした際の自動テスト対象外だから今後改修を行った時にデグレードに気づけない危険性もはらんでいます。
(毎回動作確認してＯＫなこと確認します！なんて精神論では忘れる危険性もありますし、、、自動化に任せた方が断然楽です)

2022-07-15 05:55 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> -                        Console.WriteLine()
> 2ca69bc24fd6156237a220fee970c301ce73f7af : 整数のみを通す入力チェックの追加

不要な差分含んでませんか？これは入力チェックの追加にかかわらない、表示上内容修正では？

2022-07-15 05:59 UTC, nabemasamasa requested changes
コーディングルール違反があったのにコメント忘れてた、追加

2022-07-15 05:59 UTC, nabemasamasa commented on HitAndBlow/QuestionNumberRegister.vb
> +    Public Function RandomNumberSet() As String
[Q] ランダムって動詞ですか？

[knowledge/VB.NET.コーディングルール.md#(17) メソッド名](https://github.com/daniel-software-tokyo/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#17-%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E5%90%8D)

2022-07-17 23:48 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
今後じゃなくて、今直してください。[MUST]ラベルなので。
もうやっちゃったものはしょうがないよねーで済まさないでください。

2022-07-18 05:52 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
（読んでないのかな、それとも読んだのに無視してるのかな）

2022-07-18 06:15 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    End Function
(コメント読んだらまずは「修正します」などコメント残してほしい……。
修正したら「修正しました <commit-hash>」残してほしい……。
すぐ済む修正(0.5hとか)ならすぐPushしちゃってしれっと「修正しました」でもいいけど、コメントされて時間経ってるなら一言欲しい……。
わからない、詰まってるなら相談するとか、聞いてほしい……………)

2022-07-18 06:17 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +    End Function
申し訳ありません。
気付いておりませんでした。

コミットがひとまとまりになっていることに関しての修正なのですが、私が１回目にコミットをしたのが機能を一通り実装してからでした。コミットをするタイミングがいまいちわからず、機能を一通り実装してからコミットをすると判断しました。質問をするべきでした。大変申し訳ございません。

この状態からでもコミットの修正はできるのでしょうか？
もしも可能なのであれば、方法を教えていただきたいです。

2022-07-18 06:19 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
`$ git reset`を使うことで、コミットを取り消して変化点をコミット前の状態に戻すことができます。

2022-07-18 06:20 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
（ちなみにここにコメントしたから他の指摘にはもうコメント要らんやろーとか考えてませんよね？）

2022-07-18 06:30 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    End Function
[git.基本#コミットを分割したい](https://github.com/daniel-software-tokyo/knowledge/blob/master/git/git.%E5%9F%BA%E6%9C%AC.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%82%92%E5%88%86%E5%89%B2%E3%81%97%E3%81%9F%E3%81%84)

むしろ、いったん今のソースを適当なブランチ作って退避させといて、masterにreset --hardしてつまみ食いして再現した方が速そう。

2022-07-18 06:44 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +    End Function
ありがとうございます。
修正いたします。

コメントへの返信につきましては申し訳ありません。
作業を開始する前に返信すべきでした。

2022-07-18 06:51 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
（ちなみにごめんなさいしたから既存の指摘にはもう返信要らんやろーとか考えてませんよね？）

2022-07-18 06:51 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +    Public Function RandomNumberSet() As String
レビューありがとうございます。
コミットがひとまとまりになっている部分の修正が終わり次第ご指摘を頂いた
・コミットメッセージとコードの差分の内容
・ファイル名とクラス名の不一致
・入力チェックのメソッド抽出
・表示上内容修正
・コーディングルール違反
の修正いたします。

2022-07-18 06:55 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberRegister.vb
> +    Public Function RandomNumberSet() As String
（できれば一括じゃなくて個別に返信してくれたほうが読む側としては何の指摘に対して修正するのかわかるから嬉しい）

2022-07-18 06:58 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +    Public Function RandomNumberSet() As String
ご指摘ありがとうございます。
コメントの修正をいたします。

2022-07-18 07:14 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +        Const GAME_NUMBER As Integer = 4
レビューありがとうございます。
コミットがひとまとまりになっている部分の修正が終わり次第ご指摘を頂いた
コミットメッセージとコードの差分の内容の修正いたします。

2022-07-18 07:15 UTC, danielkaneko commented on HitAndBlowTest/MainTest.vb
> -    <Test>
レビューありがとうございます。
コミットがひとまとまりになっている部分の修正が終わり次第ご指摘を頂いたテストクラスの差分の修正いたします。

2022-07-18 07:15 UTC, danielkaneko commented on HitAndBlowTest/HitAndBlowTest.vbproj
> +    <Compile Include="QuestionNumberRegisterTest].vb" />
レビューありがとうございます。
コミットがひとまとまりになっている部分の修正が終わり次第ご指摘を頂いたファイル名とクラス名の不一致の修正いたします。

2022-07-18 07:17 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +                        If answerNumber.Length = 4 And answerNumber.Contains(".") = False Then
レビューありがとうございます。
コミットがひとまとまりになっている部分の修正が終わり次第ご指摘を頂いた入力チェックのメソッド抽出の処理をいたします。

2022-07-18 07:17 UTC, danielkaneko commented on HitAndBlow/Main.vb
> -                        Console.WriteLine()
レビューありがとうございます。
コミットがひとまとまりになっている部分の修正が終わり次第ご指摘を頂いた表示上内容修正のコミットの追加をいたします。

2022-07-19 02:07 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +    End Function
コミットの修正についてなんですけれども、不安が残るので手順を確認したいです。。
・コミットのリセット(「Hit&Blowを遊べるようにするため」でreset --hard)
・ファイルの編集
・随時コミット
このような手順でよいでしょうか？

2022-07-19 02:19 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
違います。`git reset --hard`は「gitの操作を無かったことにする」コマンドです。
`git reset`は「コミットを無かったことにする。但し変化点は維持する」コマンドです。
`git reset`で、取り消したいコミットの1つ前（指定したコミットの次までをresetする為）を指定してください。

2022-07-19 02:25 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
ファイルの編集って、なんでしょうか？
ソースファイルをいちから書き直すことでしょうか？
それともgitのステージング作業のことでしょうか？

前者だとしたら、その操作で大丈夫です。
後者だとしたら、`git reset --hard`では変更内容も消し飛んでしまうので`git reset`を使ってください。

2022-07-19 02:36 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +    End Function
ファイルの編集はソースファイルを書き直すという認識です。

ソースファイルを書き直す際に@nabemasamasa からいただいた
・ファイル名とクラス名の不一致
・入力チェックのメソッド抽出
・コーディングルール違反
これらの指摘の修正もしつつ作業をしてもよいでしょうか？

2022-07-19 02:39 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
はい。構いません。
・・・え？Main.vbに全部ベタ書きは直さない？

2022-07-19 02:42 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +    End Function
申し訳ありません。書き忘れていました。
そこも直します。

2022-07-25 08:48 UTC, danielkaneko commented
@nabemasamasa 
@Takatatsu9 

再コミットしましたので、レビューをよろしくお願いいたします

2022-07-26 00:50 UTC, Takatatsu9 requested changes
Done

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberRegister.vb
> +        Dim tmp As String
[IMO] もうちょっと具体的な変数名だといいなあ。
`r`→`random`
`random`→`randomNum`
みたいな

[MUST] `tmp`、`temp`のような何を指してるのか全くわからない変数名はNGです

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberRegister.vb
> +            randam = r.Next(0, i)
[IMO] 上の`Dim random As Integer`はここで宣言するのもアリです。
このFor文内でしか使わない変数なので。

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberRegister.vb
> +        '頭4つ代入
[IMO] 同様に`Dim hbQuestion As String = ""`もここで宣言すると良いです。
ここ以降でしか使わないので。

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +
[IMO] 無駄な空白行多すぎ・・・

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Loop
[IMO] `Loop 抜ける条件式`って書けばいいのでは？

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 1
[Q] `1`ってなんですか？

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 0
[Q] `0`ってなんですか？

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
[Q] `1`ってなんですか？

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 0
[Q] `0`ってなんですか？

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberRegister.vb
> +﻿Public Class QuestionNumberRegister
[IMO] `Register`（登録するもの）ではないと思う。生成するものじゃないかな。

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
[MUST] `Public`ならコメントつけてください

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
[MUST] 型が書かれていません

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
[MUST] `Check〜`じゃチェックした結果、どういうときに何が返されるのか全く読み取れないのでダメです。
コーディングルールを読み返してください。

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/HitCount.vb
> +﻿Public Class HitCount
[nits] これだとカウントした値を入れるものとも思えちゃうので、`HitCounter`のほうがいいかも

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/HitCount.vb
> +    Public Function CountHit(answerNumber As String, questionNumber As String)
こっちはこのメソッド名のままでOK。「ヒットを数える」で意味が通るから

2022-07-26 00:50 UTC, Takatatsu9 commented on HitAndBlow/BlowCount.vb
> +        For i As Integer = 0 To 3
[IMO] `For Each`というものがありましてね。
`For Each num As Char In answerNumber.ToCharArray()`と書くとですね、
例えば`answerNumber`が`8506`だとしたら`num`に1巡目は`8`、2巡目は`5`、と1つずつ入れてくれるんですよ。

（もしかしたら`ToCharArray`要らないかもしれない）

2022-07-26 00:52 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberRegister.vb
> +            randam = r.Next(0, i)
よく見たらrand**a**mで草

2022-07-26 00:54 UTC, nabemasamasa requested changes
NG、Publicなメソッドにはコメント必須

2022-07-26 00:54 UTC, nabemasamasa commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
[MUST] あ、Publicなメソッドなのにコメントがない

2022-07-26 00:54 UTC, nabemasamasa commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
Functionなのに、戻り値の型が未定義、それなのにエラーにならない。
これはプロジェクトの設定が悪い気がする。

静的型付け言語である場合、ちゃんと型を定義してあげることで、処理速度の向上や、予期せぬ型になってしまう危険性の回避を見込めます。
メソッドの戻り値の型が定義されてないとエラーになるようにしたいです。

2022-07-26 00:54 UTC, nabemasamasa commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
[Q] `CheckDigitInteger`って、読み解く限り、`4桁の整数かどうか`を返すメソッドですが、1と0以外の値を取ることってありますか？

2022-07-26 00:54 UTC, nabemasamasa commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
`CheckNumbersOnly`の戻り値の型はStringなのに、ダブルクォートで囲まれてない、文字列じゃなく数字の1を返してます。けど、エラーにならないっぽい、、、なぜ？

2022-07-26 00:54 UTC, nabemasamasa commented on HitAndBlowTest/DigitIntegerCheckTest.vb
> +        Dim actual As String = dic.CheckDigitInteger(1234)
[nits] 引数がString型なのに、テストだと数値を与えてる。
ちゃんと文字列型かつ、記号や数字以外の文字もテストほしいです。

2022-07-26 01:04 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +        Dim tmp As String
レビューありがとうございます。
変数名修正いたします。

2022-07-26 01:04 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +            randam = r.Next(0, i)
レビューありがとうございます。
変数の宣言場所を修正いたします。

2022-07-26 01:06 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +        '頭4つ代入
レビューありがとうございます。
上記と同様に変数の宣言場所を修正いたします。

2022-07-26 01:07 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +
レビューありがとうございます。
余分な空白を削除いたします。

2022-07-26 01:08 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +        Loop
レビューありがとうございます。
繰り返しの条件式を追加し修正いたします。

2022-07-26 01:09 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
レビューありがとうございます。
型を記述いたします。

2022-07-26 01:10 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
レビューありがとうございます。
メソッド名を修正いたします。

2022-07-26 01:10 UTC, danielkaneko commented on HitAndBlow/HitCount.vb
> +﻿Public Class HitCount
レビューありがとうございます。
クラス名を修正いたします。

2022-07-26 01:10 UTC, danielkaneko commented on HitAndBlow/HitCount.vb
> +    Public Function CountHit(answerNumber As String, questionNumber As String)
レビューありがとうございます。
承知いたしました。

2022-07-26 01:12 UTC, danielkaneko commented on HitAndBlow/BlowCount.vb
> +        For i As Integer = 0 To 3
レビューありがとうございます。
For Eachの書き方に修正いたします。

2022-07-26 01:13 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
レビューありがとうございます。
Publicなメソッドへのコメントを追加いたします。

2022-07-26 01:14 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
レビューありがとうございます。
プロジェクトの設定を見直し、修正いたします。

2022-07-26 01:15 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
レビューありがとうございます。
0と１以外の値を取ることはありません。

2022-07-26 01:15 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
レビューありがとうございます。
戻り値をダブルクォートで囲み、修正いたします。

2022-07-26 01:17 UTC, danielkaneko commented on HitAndBlowTest/DigitIntegerCheckTest.vb
> +        Dim actual As String = dic.CheckDigitInteger(1234)
レビューありがとうございます。
文字列型かつ、記号や数字以外の文字のテストを追加いたします。

2022-07-26 01:33 UTC, nabemasamasa commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
`4桁の整数である`が0、`4桁の整数ではない`が1でしたっけ？
例えば、Mainに書かれてる`CheckDigitNumber  = 1`って、一目見た時に1が`4桁の整数である`を示してるって一目見てわかりやすいですか？
である/でないを示すだけのメソッドだけど、数値である必要ってありますか……？

2022-07-26 01:35 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 1
無視しないで

2022-07-26 01:39 UTC, nabemasamasa commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
まずは、暗黙的な型変換を許さないようにしてほしいです。
恐らく、`Return 1`してるけど、戻り値の型はStringだから、コードの実行時によしなに戻り値の型のString型に変換している気がする。
このメソッドをウォッチ式で見たら、String型で`"1"`か`"0"`か取得できそう。

2022-07-26 01:45 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +            randam = r.Next(0, i)
変数名がrandamであったのはスペルミスですので、randomに直したうえで修正いたします。

2022-07-26 01:49 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
確かに1と0では一目見たときに判別がつきづらいように思えました。
CheckDigitNumberにて戻り値をtrue、falseに変更しようと考えたのですが、いかがでしょうか？

2022-07-26 02:00 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
承知いたしました。
暗黙的な型変換を防ぐ手段として、ソリューションエクスプローラーのプロパティの設定を変更しようと考えているのですが、いかがでしょうか？

2022-07-26 02:11 UTC, nabemasamasa commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
どのプロパティですか？
Shift+Windows+Sで変更しようとしている「ソリューションエクスプローラーのプロパティの設定」のスクリーンショットを撮って、コメントに貼り付けてほしいです。
[knowledge/Windows10.md#画面領域を指定してクリップボードにコピー](https://github.com/daniel-software-tokyo/knowledge/blob/master/Windows10.md#%E7%94%BB%E9%9D%A2%E9%A0%98%E5%9F%9F%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%A6%E3%82%AF%E3%83%AA%E3%83%83%E3%83%97%E3%83%9C%E3%83%BC%E3%83%89%E3%81%AB%E3%82%B3%E3%83%94%E3%83%BC)

2022-07-26 02:17 UTC, nabemasamasa commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
いいと思います。


ところで独り言なんですが、Booleanを返すメソッドって専用のコーディングルールがあるんですよね(返答不要)

2022-07-26 02:25 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 1
無視しないで・・・

2022-07-26 02:48 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
![image](https://user-images.githubusercontent.com/108507359/180912047-f8692870-a0ba-4ac0-a32c-789c9c10e5f9.png)

調べた結果、プロパティのOption Strictの設定を変更するというものがありましたので、そちらを試そうとしています。

2022-07-26 02:51 UTC, nabemasamasa commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
HitAndBlowプロジェクトのプロパティのコンパイルの設定に、OptionStrictがいるのでそれをOnに変更するという事ですね。
はい、まさしくそれなので、変更してほしいです。
でも、HitAndBlowだけじゃなくて、HitAndBlow.Testも設定してほしいです。

2022-07-26 04:26 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
ありがとうございます。
承知いたしました。

2022-07-26 06:33 UTC, Takatatsu9 commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 1
<img width="300" alt="スクリーンショット 2022-07-26 11 53 32" src="https://user-images.githubusercontent.com/50448373/180939131-502b6914-617f-4cce-9b94-33134f0fdb7c.png">

2022-07-26 06:50 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 1
レビューありがとうございます。
返信が遅くなり申し訳ありません。
戻り値の1はMainにて入力チェックの判定使う数字になりますが、
@nabemasamasa より同様の指摘を頂いておりまして、戻り値をtrue、falseにする形での修正を考えております。

2022-07-26 06:51 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 0
レビューありがとうございます。
返信が遅くなり申し訳ありません。
戻り値の0はMainにて入力チェックの判定使う数字になりますが、
@nabemasamasa より指摘を頂いておりまして、戻り値をtrue、falseにする形での修正を考えております。

2022-07-26 06:52 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
レビューありがとうございます。
返信が遅くなり申し訳ありません。
戻り値の1はMainにて入力チェックの判定使う数字になりますが、
@nabemasamasa より指摘を頂いておりまして、戻り値をtrue、falseにする形での修正を考えております。

2022-07-26 06:52 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 0
レビューありがとうございます。
返信が遅くなり申し訳ありません。
戻り値の0はMainにて入力チェックの判定使う数字になりますが、
@nabemasamasa より指摘を頂いておりまして、戻り値をtrue、falseにする形での修正を考えております。

2022-07-26 06:53 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +﻿Public Class QuestionNumberRegister
レビューありがとうございます。
返信が遅くなり申し訳ありません。
クラス名を適切なものに修正いたします。

2022-07-26 06:54 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
レビューありがとうございます。
返信が遅くなり申し訳ありません。
パブリックなメソッドへコメントを追加いたします。

2022-07-27 04:56 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
OptionStrict の設定変更で生じるエラーについては、設定の変更に伴うエラー修正のような形でコミットを一つにまとめて修正してよろしいでしょうか？

2022-07-27 05:30 UTC, nabemasamasa commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
はい、コミットのルールは"エラーが起こらないコミットにすること"なので、コンパイルが通らないなら修正を含めるべきです。

ついでに、コミットメッセージの３行目あたりに、「併せてエラーになる箇所も修正」など補足しておいてください。

2022-07-27 05:32 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
ありがとうございます。
承知いたしました。

2022-07-28 08:02 UTC, Takatatsu9 commented
@nabemasamasa 
もし明日レビュー全部OKで @danielkaneko が手持ち無沙汰になるようでしたら、
光一さんのH&Bリポジトリにある追加要望Issueからなにか1つ与えといてください。

2022-07-29 00:12 UTC, danielkaneko commented
@nabemasamasa 
@Takatatsu9 
修正を行いましたので、レビューをお願い致します。

2022-07-29 00:13 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +        Dim tmp As String
修正を行いました。
コミットハッシュ：dade54517d1328c1357818399fa883034a47d4b6

2022-07-29 00:13 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +            randam = r.Next(0, i)
修正を行いました。
コミットハッシュ：5ed37bdfceb63ad548352fe3786be16f4314f100

2022-07-29 00:14 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +        '頭4つ代入
修正を行いました。
コミットハッシュ：36cf5ef9a3d230ffac9b76251f1bbbc5bd41a2d5

2022-07-29 00:14 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +
修正を行いました。
コミットハッシュ：9a4f43dc60fcf0935087985f92861d22f6540f88

2022-07-29 00:15 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +        Loop
修正を行いました。
コミットハッシュ：7855e6feec29bd71ce7b66b01f4826974de7fcd7

2022-07-29 00:15 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
修正を行いました。
コミットハッシュ：ee6a7f36715adffbc72878ad50c396a351e21bed

2022-07-29 00:16 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
修正を行いました。
コミットハッシュ：ee6a7f36715adffbc72878ad50c396a351e21bed

2022-07-29 00:17 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 1
修正を行いました。
コミットハッシュ：3c73e8f50ca1abec7dafc7b2dc9e4d4d9e8d957a

2022-07-29 00:17 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +            Return 0
修正を行いました。
コミットハッシュ：3c73e8f50ca1abec7dafc7b2dc9e4d4d9e8d957a

2022-07-29 00:17 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
修正を行いました。
コミットハッシュ：e0ed30b03ccc67ed37c3e1db383cd500fe749a52

2022-07-29 00:18 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 0
修正を行いました。
コミットハッシュ：e0ed30b03ccc67ed37c3e1db383cd500fe749a52

2022-07-29 00:18 UTC, danielkaneko commented on HitAndBlow/QuestionNumberRegister.vb
> +﻿Public Class QuestionNumberRegister
修正を行いました。
コミットハッシュ：1679a3780e8cd975de24d8b728e6875349fc7279

2022-07-29 00:19 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
修正を行いました。
コミットハッシュ：970a92c6dd8796e5b4ae04b18215c7b0aa320d5c

2022-07-29 00:20 UTC, danielkaneko commented on HitAndBlow/HitCount.vb
> +﻿Public Class HitCount
修正を行いました。
コミットハッシュ：05e33e1ac38785ef713159b620596ec9a5d0700c

2022-07-29 00:21 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
修正を行いました。
コミットハッシュ：970a92c6dd8796e5b4ae04b18215c7b0aa320d5c

2022-07-29 00:22 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
修正を行いました。
コミットハッシュ：ee6a7f36715adffbc72878ad50c396a351e21bed

2022-07-29 00:23 UTC, danielkaneko commented on HitAndBlow/DigitIntegerCheck.vb
> +    Public Function CheckDigitInteger(answerNumber As String)
修正を行いました。
コミットハッシュ：3c73e8f50ca1abec7dafc7b2dc9e4d4d9e8d957a

2022-07-29 00:23 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
> +            Return 1
修正を行いました。
コミットハッシュ：8dc647904d06be068cb3f23d80d9ca73c2260b29

2022-07-29 00:24 UTC, danielkaneko commented on HitAndBlowTest/DigitIntegerCheckTest.vb
> +        Dim actual As String = dic.CheckDigitInteger(1234)
修正を行いました。
コミットハッシュ：8e393bf300ef642080b7342eb590378b37a8e54a

2022-07-29 00:50 UTC, danielkaneko commented on HitAndBlow/BlowCount.vb
> +        For i As Integer = 0 To 3
修正を行いました。
コミットハッシュ： 7b1eaba

2022-07-29 01:10 UTC, nabemasamasa commented
(そういえば、PR作るときに書いたDescriptionのToDoってもう対応済みな気がする……)

2022-07-29 01:25 UTC, nabemasamasa reviewed
done

2022-07-29 01:25 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
> 答えの数字生成メソッド名の修正

[Q] ここの差分って、Renameですか？

2022-07-29 01:25 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
[Q] これを`Off`にすることで何がうれしくなるんですか？

2022-07-29 01:25 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="QuestionNumberGenerater.vb" />
あっ懐かしい私もこのTypo昔してた

2022-07-29 01:25 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Loop While Not noc.CheckNumbersOnly(answerNumber) AndAlso Not dic.IsFourDigitInteger(answerNumber)
[Q] なんかRename混ざってますけど、このコミットってコンパイル通りますか？

2022-07-29 01:43 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
レビューありがとうございます。
コミットを分けて修正いたします。

2022-07-29 01:51 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
レビューありがとうございます。
特にうれしくなることはないと思います。
誤って設定を変更してしまい、気付かずコミットしてしまいました。
Onに設定しなおします。

2022-07-29 01:57 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +            Loop While Not noc.CheckNumbersOnly(answerNumber) AndAlso Not dic.IsFourDigitInteger(answerNumber)
レビューありがとうございます。
確認してみたところ、通りませんでした。
修正いたします。

2022-07-29 01:59 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="QuestionNumberGenerater.vb" />
レビューありがとうございます。
コーディングルールを参考にした名づけを行っても、その名前が処理に対してふさわしいかどうかで不安が残ります。

2022-07-29 02:03 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="QuestionNumberGenerater.vb" />
えぇと、 :x: Generat **e** r  :o: Generat **o** r

2022-07-29 02:04 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="QuestionNumberGenerater.vb" />
もしかして、そもそもコーディングルールがTypoしてたりする？？？

2022-07-29 02:09 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="QuestionNumberGenerater.vb" />
Generatorにつきましては、コーディングルールが原因ではなく私のスペルミスになります。
修正いたします。

2022-07-29 02:39 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
この差分のコミットを分けるにあたり、コミットメッセージをどのようにつければよいかわかりません。
どの操作でこの差分が生まれるのか調べているのですが、いまいちわからない状況です。

2022-07-29 02:43 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
えぇと、そのコミットの前の状態で、プロジェクトの設定をスクリーンショットして、
該当コミットとで差分を見比べてみるのはいかがでしょうか？

2022-07-29 02:44 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
と思ったら、順番が変わってるだけか。たぶん、警告を弄った事で順番が変わったんですかね？
となると、果たしてこのコミットは必要……？？？

2022-07-29 03:03 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
順番が変わっているだけなので必要ないように思えます。
ですので、差分の見比べをして、差分が発生しないように修正を試みようと思います。

2022-07-29 06:03 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
修正いたしました。
コミットハッシュ： 9ba7ac7

2022-07-29 06:12 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
修正いたしました。
コミットハッシュ： 9ba7ac7

2022-07-29 06:12 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="QuestionNumberGenerater.vb" />
修正いたしました。
コミットハッシュ： c81f906

2022-07-29 06:13 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +            Loop While Not noc.CheckNumbersOnly(answerNumber) AndAlso Not dic.IsFourDigitInteger(answerNumber)
修正いたしました。
コミットハッシュ： 46497d9

2022-07-29 06:19 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
> 順番が変わっているだけなので必要ないように思えます。
> ですので、差分の見比べをして、差分が発生しないように修正を試みようと思います。

コミットハッシュから飛んで確認した感じ、差分発生してません……？

2022-07-29 06:29 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
レビューありがとうございます。
申し訳ありません。
テストプロジェクトの修正が抜けておりました。
急ぎ、修正いたします。

2022-07-29 07:04 UTC, danielkaneko commented on HitAndBlow/HitAndBlow.vbproj
> +    <NoWarn>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</NoWarn>
修正いたしました。
コミットハッシュ： 70477e6

2022-07-29 07:29 UTC, nabemasamasa reviewed
Done

2022-07-29 07:30 UTC, nabemasamasa approved these changes

2022-07-29 07:32 UTC, nabemasamasa commented
OKです。達也さんのレビューもOKなら、コミット整理しちゃいましょう。

2022-08-01 00:56 UTC, Takatatsu9 reviewed
Done

2022-08-01 00:56 UTC, Takatatsu9 commented on HitAndBlow/HitCounter.vb
> +﻿Public Class HitCounter
> ヒット数計算クラス名の修正

コミットコメントはなぜその変更に至ったかの理由を書いたほうがいいですね。次からでいいです。

2022-08-01 00:56 UTC, Takatatsu9 commented on HitAndBlow/HitCounter.vb
> +    ''' 入力した数字に対するヒット数の計算
[Q/IMO] 計算した後どうするんですか？戻り値があるメソッドのコメントでこれは少し説明不足です。

2022-08-01 00:56 UTC, Takatatsu9 commented on HitAndBlow/NumbersOnlyCheck.vb
>      Public Function CheckNumbersOnly(answerNumber As String) As Boolean
[MUST] あれ、これまだ指摘してなかったでしたっけ。
`Check〜`というメソッド名はチェックしてOKがTrueなのかNGがTrueなのかわからないからダメです。

2022-08-01 00:56 UTC, Takatatsu9 commented on HitAndBlow/QuestionNumberGenerater.vb
> +    ''' CPUによる数字4桁の設定
[IMO] うーん、`SetRandomNumber`とコメントで意味が違くない？
`Set`（クラスが持つメンバ変数への値の設定）でもないし。

2022-08-01 01:04 UTC, Takatatsu9 commented on HitAndBlow/NumbersOnlyCheck.vb
>      Public Function CheckNumbersOnly(answerNumber As String) As Boolean
前別のところで指摘してたけど、ここが指摘されてないからって放置されてら

2022-08-01 05:22 UTC, danielkaneko commented on HitAndBlow/HitCounter.vb
> +﻿Public Class HitCounter
レビューありがとうございます。
承知いたしました。
次回以降記載させていただきます。

2022-08-01 05:26 UTC, danielkaneko commented on HitAndBlow/HitCounter.vb
> +    ''' 入力した数字に対するヒット数の計算
レビューありがとうございます。
ヒット数を計算し、ヒット数を返します。
コメントを修正いたします。

2022-08-01 05:27 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
>      Public Function CheckNumbersOnly(answerNumber As String) As Boolean
レビューありがとうございます。
メソッド名を修正いたします。

2022-08-01 05:27 UTC, danielkaneko commented on HitAndBlow/QuestionNumberGenerater.vb
> +    ''' CPUによる数字4桁の設定
レビューありがとうございます。
コメントを修正いたします。

2022-08-01 06:39 UTC, danielkaneko commented on HitAndBlow/HitCounter.vb
> +    ''' 入力した数字に対するヒット数の計算
修正しましたのでレビューをお願いいたします。
コミットハッシュ： bb2a67e

2022-08-01 06:40 UTC, danielkaneko commented on HitAndBlow/NumbersOnlyCheck.vb
>      Public Function CheckNumbersOnly(answerNumber As String) As Boolean
修正しましたのでレビューをお願いいたします。
コミットハッシュ： 15d7f99

2022-08-01 06:40 UTC, danielkaneko commented on HitAndBlow/QuestionNumberGenerater.vb
> +    ''' CPUによる数字4桁の設定
修正しましたのでレビューをお願いいたします。
コミットハッシュ： f23aa4f

2022-08-01 06:42 UTC, Takatatsu9 approved these changes
Done

2022-08-01 06:53 UTC, nabemasamasa reviewed
Done

2022-08-02 06:01 UTC, danielkaneko commented
@Takatatsu9 
@nabemasamasa 

コミット整理を行いましたので、ご確認をお願い致します。

2022-08-02 06:48 UTC, Takatatsu9 reviewed
Done

2022-08-02 06:48 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +
また余計な改行が・・・
（というか1行おきに改行挟むの好きなんですね。読みにくくなるから嫌いだけど（個人の感想））

2022-08-02 06:56 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +
レビューありがとうございます。
余計な改行を削除いたします。

指摘を頂いた箇所以外の1行おきに挟まれている改行は消したほうが良いでしょうか？

2022-08-02 07:52 UTC, nabemasamasa reviewed
Done

2022-08-02 07:52 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim blow As Integer
コードレビューとコミット整理によって、差分がきれいになってコード水準が上がった結果、今度は別の事が気になる……。
[Q] 変数宣言を全部ひとまとめにしてる理由ってなんですか？

2022-08-02 08:07 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +        Dim blow As Integer
レビューありがとうございます。
変数宣言をひとまとめにしている理由は、私の癖になります。
変数の宣言場所につきましては、指摘を頂いたことがあるにもかかわらずコミット整理の段階でまとめてしまいました。
変数の宣言場所をその変数を使う直前で宣言する形に修正いたします。

2022-08-02 23:32 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim blow As Integer
了解です、なら、修正お願いします。。(指摘してた事すっかり忘れてた……)

2022-08-02 23:35 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +
消したほうがいいですが、全てではないです。
1つのやりたいことをやってる範囲内は詰め、別のことを始めるときには改行を挟むというのがいいですね。

2022-08-02 23:54 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +
ありがとうございます。
そのように修正いたします。

2022-08-03 01:41 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +
修正いたしました。
コミットハッシュ： 1859362

2022-08-03 01:41 UTC, danielkaneko commented on HitAndBlow/Main.vb
> +        Dim blow As Integer
修正いたしました。
コミットハッシュ： 9007192

2022-08-03 01:45 UTC, Takatatsu9 reviewed
Done

2022-08-03 01:45 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +
とても見やすくなりました

2022-08-03 02:06 UTC, nabemasamasa reviewed
Done!

2022-08-03 04:31 UTC, merged